### ISSUE TITLE
Travis-CI Update not running

### ISSUE THREAD

**Issue by 7karathrace** [firsttris/repository.sendtokodi.python3#1]
Hi. I was under the impression that Travis-CI Update should bump the addon verson of sendtokodi whenever there are updates to youtube-dl.

But this hasn't happened for three months and I'm finding some newer youtube streams don't play.

Does Travis need restarting?

**Comment by firsttris** [comment]
i think we need to migrate to travis.com

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by firsttris** [comment]
my understandig is there is no longer a free version of travis-ci

i need to migrate to github actions

**Comment by firsttris** [comment]
build is now working again with githut actions
