### ISSUE TITLE
Youtube links not playable

### ISSUE THREAD

**Issue by popcornmix** [firsttris/repository.sendtokodi.python3#2]
Youtube has implemented throttling to non-preferred clients, that makes real time playback (almost) impossible.
See for example:
https://github.com/anxdpanic/plugin.video.youtube/issues/163
https://github.com/ytdl-org/youtube-dl/issues/29326

There are two possible fixes, you can supply the magic `&n=<val>` parameter to fetch link, or you can identify as Android.
There is no fix in youtube-dl, but yt-dlp does have a fix (the Android one)

The following replaces the embedded youtube-dl with yt-dlp (which is a compatible fork), and fixes the throttling issue.
```
wget --no-check-certificate -qO- https://github.com/yt-dlp/yt-dlp/archive/refs/heads/master.zip | unzip - 'yt-dlp-master/yt_dlp/*' -d '/tmp/' && \
rm -rf /~/.kodi/addons/plugin.video.sendtokodi.python3/youtube_dl && \
mv /tmp/yt-dlp-master/yt_dlp/ ~/.kodi/addons/plugin.video.sendtokodi.python3/youtube_dl && \
rm -rf /tmp/tmp/yt-dlp-master
```

**Comment by firsttris** [comment]
https://github.com/firsttris/plugin.video.sendtokodi/issues/36
